### ISSUE TITLE
这是什么问题伙计

### ISSUE THREAD

**Issue by qiangua2460** [toraidl/hyperos_port#30]
2024-11-14 20:47:07 - check_target_files_vintf.py - WARNING : PRODUCT_ENFORCE_VINTF_MANIFEST is not set, skipping checksTraceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ofks/hyperos_port/otatools/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "ota_from_target_files.py", line 1534, in <module>
  File "ota_from_target_files.py", line 1505, in main
  File "ota_from_target_files.py", line 1043, in GenerateAbOtaPackage
  File "ota_utils.py", line 290, in GetPackageMetadata
  File "ota_utils.py", line 252, in UpdateDeviceState
  File "ota_utils.py", line 241, in UpdatePartitionStates
  File "common.py", line 559, in GetPartitionBuildProp
common.ExternalError: couldn't find ro.vendor.build.date.utc in vendor.build.prop

**Comment by toraidl** [comment]
完整的日志
